export const SKILL_TAXONOMY = {
  version: "1.1.0",
  released: "2026-09-01",
  aliases: {
    "amazon web services": ["amazon web services", "aws", "aws cloud", "aws multi cloud", "aws security"],
    "microsoft azure": ["microsoft azure", "azure", "azure cloud"],
    "google cloud platform": ["google cloud platform", "google cloud", "gcp"],
    kubernetes: ["kubernetes", "k8s"],
    "continuous integration and delivery": ["continuous integration", "continuous delivery", "continuous deployment", "ci cd", "cicd"],
    "generative ai": ["generative ai", "genai", "gen ai", "large language models", "large language model", "llms", "llm"],
    "machine learning": ["machine learning", "ml"],
    "machine learning operations": ["machine learning operations", "mlops", "ml ops"],
    "artificial intelligence governance": ["artificial intelligence governance", "ai governance", "responsible ai", "responsible artificial intelligence"],
    "identity and access management": ["identity and access management", "identity access management", "iam"],
    "microsoft entra id": ["microsoft entra id", "entra id", "azure active directory", "azure ad"],
    "security information and event management": ["security information and event management", "siem"],
    "infrastructure as code": ["infrastructure as code", "iac"],
    "threat modelling": ["threat modelling", "threat modeling"],
    "risk management": ["risk management", "risk assessment", "risk assessments"],
    "stakeholder management": ["stakeholder management", "stakeholder engagement"],
    "incident response": ["incident response", "incident management"],
    "data governance": ["data governance", "information governance"],
    "vector databases": ["vector databases", "vector database", "vector dbs", "vector db"],
    "open policy agent": ["open policy agent", "openpolicyagent", "opa"],
    opentelemetry: ["opentelemetry", "open telemetry", "otel"],
    "low rank adaptation": ["low rank adaptation", "lora", "qlora", "fine tuning lora", "fine tuning qlora"],
    "static application security testing": ["static application security testing", "sast"],
    "dynamic application security testing": ["dynamic application security testing", "dast"],
    "security orchestration automation and response": ["security orchestration automation and response", "soar", "soar automation"],
    "third party risk management": ["third party risk management", "third party risk", "tprm"],
    "business continuity management": ["business continuity management", "business continuity planning", "bcm"],
    "mobile device management": ["mobile device management", "mdm", "intune mdm"],
    "information technology service management": ["information technology service management", "it service management", "itsm"],
    "model cards": ["model cards", "model card", "model card specification"],
  } satisfies Record<string, readonly string[]>,
} as const;

export const SKILL_TAXONOMY_VERSION = SKILL_TAXONOMY.version;

